import { Apple, Leaf, Container, Beef, Fish, Droplet, Wheat, Slice, CupSoda, Package } from 'lucide-react';

export const getCategoryIcon = (category, name) => {
    const text = (`${category || ''} ${name || ''}`).toLowerCase();

    if (text.includes('fruta') || text.includes('manzana') || text.includes('limon') || text.includes('limón') || text.includes('naranja') || text.includes('platano') || text.includes('plátano') || text.includes('fresa') || text.includes('uva') || text.includes('pera') || text.includes('sandía') || text.includes('sandia') || text.includes('melon') || text.includes('melón') || text.includes('kiwi') || text.includes('piña') || text.includes('pina') || text.includes('mango') || text.includes('cereza') || text.includes('melocoton') || text.includes('melocotón') || text.includes('mandarina') || text.includes('ciruela') || text.includes('frambuesa') || text.includes('arandano') || text.includes('arándano') || text.includes('aguacate') || text.includes('fruta')) return Apple;

    if (text.includes('verdura') || text.includes('lechuga') || text.includes('tomate') || text.includes('cebolla') || text.includes('vegetal') || text.includes('zanahoria') || text.includes('patata') || text.includes('pimiento') || text.includes('ajo') || text.includes('brócoli') || text.includes('brocoli') || text.includes('espinaca') || text.includes('calabacin') || text.includes('calabacín') || text.includes('coliflor') || text.includes('judia') || text.includes('judía') || text.includes('calabaza') || text.includes('puerro') || text.includes('apio') || text.includes('pepino') || text.includes('berenjena') || text.includes('alcachofa') || text.includes('acelga') || text.includes('repollo') || text.includes('ensalada') || text.includes('seta') || text.includes('champiñon') || text.includes('champiñón') || text.includes('hongo')) return Leaf;

    if (text.includes('salsa') || text.includes('tomate frito') || text.includes('nata') || text.includes('ketchup') || text.includes('mayonesa') || text.includes('mostaza') || text.includes('soja') || text.includes('barbacoa') || text.includes('alioli') || text.includes('vinagreta') || text.includes('pesto') || text.includes('guacamole') || text.includes('hummus')) return Container;

    if (text.includes('carne') || text.includes('pollo') || text.includes('cerdo') || text.includes('ternera') || text.includes('filete') || text.includes('pavo') || text.includes('conejo') || text.includes('cordero') || text.includes('pato') || text.includes('salchicha') || text.includes('hamburguesa') || text.includes('chuleta') || text.includes('costilla') || text.includes('bacon') || text.includes('banceta') || text.includes('picada') || text.includes('lomo')) return Beef;

    if (text.includes('pescado') || text.includes('marisco') || text.includes('atun') || text.includes('atún') || text.includes('salmon') || text.includes('salmón') || text.includes('gambas') || text.includes('merluza') || text.includes('bacalao') || text.includes('calamar') || text.includes('pulpo') || text.includes('langostino') || text.includes('mejillon') || text.includes('mejillón') || text.includes('sardina') || text.includes('boqueron') || text.includes('boquerón') || text.includes('dorada') || text.includes('lubina') || text.includes('almeja') || text.includes('sepia') || text.includes('langosta') || text.includes('cangrejo')) return Fish;

    if (text.includes('aceite') || text.includes('especia') || text.includes('sal') || text.includes('pimienta') || text.includes('vinagre') || text.includes('oregano') || text.includes('orégano') || text.includes('pimentón') || text.includes('pimenton') || text.includes('canela') || text.includes('comino') || text.includes('curry') || text.includes('perejil') || text.includes('albahaca') || text.includes('romero') || text.includes('tomillo') || text.includes('laurel') || text.includes('azafrán') || text.includes('azafran') || text.includes('nuez moscada') || text.includes('clavo') || text.includes('aliño')) return Droplet;

    if (text.includes('pan') || text.includes('harina') || text.includes('pan rallado') || text.includes('trigo') || text.includes('cereal') || text.includes('pasta') || text.includes('arroz') || text.includes('macarrones') || text.includes('fideos') || text.includes('espaguetis') || text.includes('spaghetti') || text.includes('galleta') || text.includes('bolleria') || text.includes('bollería') || text.includes('magdalena') || text.includes('bizcocho') || text.includes('tostada') || text.includes('avena') || text.includes('maiz') || text.includes('maíz') || text.includes('quinoa') || text.includes('cereales')) return Wheat;

    if (text.includes('queso') || text.includes('embutido') || text.includes('jamon') || text.includes('jamón') || text.includes('chorizo') || text.includes('salchichón') || text.includes('loncha') || text.includes('pavo') || text.includes('lomo') || text.includes('salchicha') || text.includes('mortadela') || text.includes('salami') || text.includes('fuet') || text.includes('sobrasada') || text.includes('panceta') || text.includes('bacon') || text.includes('mozzarella') || text.includes('cheddar') || text.includes('parmesano') || text.includes('brie') || text.includes('camembert') || text.includes('gouda') || text.includes('edam') || text.includes('roquefort') || text.includes('cabra') || text.includes('oveja') || text.includes('vaca') || text.includes('feta') || text.includes('rulo') || text.includes('quesito')) return Slice;

    if (text.includes('zumo') || text.includes('leche') || text.includes('agua') || text.includes('bebida') || text.includes('liquido') || text.includes('líquido') || text.includes('refresco') || text.includes('cerveza') || text.includes('vino') || text.includes('caldo') || text.includes('cafe') || text.includes('café') || text.includes('te') || text.includes('té') || text.includes('infusion') || text.includes('infusión') || text.includes('batido') || text.includes('licor') || text.includes('cava') || text.includes('champan') || text.includes('champán') || text.includes('sidra') || text.includes('kombucha') || text.includes('bebida vegetal') || text.includes('soja') || text.includes('avena') || text.includes('almendra')) return CupSoda;

    // Default
    return Package;
};
